timezone: America/New_York

ntp_timezone: '{{ timezone }}'

locale: en_US.UTF-8

keyboard_layout: us

username: "hyoga"

root_username: "root"

shell: /usr/bin/zsh

dotfiles_repo: https://github.com/chkpwd/dotfiles