---
media_path: /mnt/media
container_path: /data
arr_uid: "1000"
arr_gid: "1000"

common_env: &common_env
  TZ: America/New_York
  PUID: "{{ arr_uid }}"
  PGID: "{{ arr_gid }}"

service_definitions:
  - name: bitwardenrs
    image: "vaultwarden/server:latest"
    ports: [8086:80]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/bitwardenrs:/data"

  - name: swag
    image: "{{ linuxserver_image }}/swag:latest"
    ports:
      - 443:443
      - 80:80
    env: 
      <<: *common_env
      URL: chkpwd.com
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: mentality@protonmail.com
    volumes:
      - "{{ configuration_path }}/swag:/config"

  - name: unifi
    image: "lumel/unifi-controller"
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '8080:8080'
      - '8085:8081'
      - '8443:8443'
      - '8843:8843'
      - '8880:8880'
      - '6789:6789'
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/unifi:/usr/lib/unifi/data"
      
  - name: filebrowser
    image: hurlenko/filebrowser
    ports:
      - 5555:8080
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/filebrowser:/config"
      - "{{ configuration_path }}/filebrowser_data:/data"

  - name: bookstack
    image: "{{ linuxserver_image }}/bookstack"
    env:
      <<: *common_env
      APP_URL: https://docs.chkpwd.com
      DB_HOST: bookstack_db
      DB_USER: bookstack
      DB_PASS: bryanswag12
      DB_DATABASE: bookstackapp
    volumes:
      - "{{ configuration_path }}/bookstack:/config"
    ports: [6875:80]

  - name: bookstack_db
    image: "{{ linuxserver_image }}/mariadb:110.4.19mariabionic-ls21"
    env:
      MYSQL_ROOT_PASSWORD: bryanswag12
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bryanswag12
    volumes:
      - "{{ configuration_path }}/bookstack_db:/config"

  - name: homer
    image: b4bz/homer
    ports: [8081:8080]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/homer:/www/assets"

  - name: code-server
    image: "{{ linuxserver_image }}/code-server"
    ports: [9443:8443]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/code:/config"
      - "{{ configuration_path }}/homer:/config/homer:rw"
      
  - name: freshrss
    image: "{{ linuxserver_image }}/freshrss:latest"
    env: "{{ common_env }}"
    ports: [8087:80]
    volumes:
      - "{{ configuration_path }}/freshrss:/config"

  - name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATION_TITLE_TAG: "Horizon"
      WATCHTOWER_SCHEDULE: "0 7 */10 * *"
      WATCHTOWER_NOTIFICATION_URL: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        32653733663266336361393539303630356133346462666131306165373861353464333264336533
        3939646531366264363836313561663230386536316331650a643434373331613964343136316461
        36336261373662656531623831633634643437366133623566393431643661373932613865363632
        6363633163326166370a393564363036633232373861393037313038326537303035396463386432
        33633661653535373239386636383765396430396638313937303735633262653736316134663336
        65616461353661396132336663313536353937366533626132613761666231356436313263333634
        30346363343138373864323930623565663036663536656239356463613336633864626666633935
        63646464353766633632366332623766333130356162623336326332383636353432653664613031
        36613465383865626531353663373965363365613031393936323265343064643463
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
