all:
  hosts:
  children:
    vsphere:
      children:
        esxi_hosts:
        vcenter:

    vcenter:
      hosts:
        ronin:

    esxi_hosts:
      hosts:
        #esx[1:3]:
        octane:
        caustic:

    guests:
      children:
        docker_hosts:
        media_server:
        printers:
      hosts:
        pathfinder:
        stable-diffusion:

    docker_hosts:
      hosts:
        mirage:
        horizon:
        valkyrie:
        crypto:

    printers:
      hosts:
        revenant:

    media_server:
      hosts:
        mirage:

    dev:
      children:
        staging:

    staging:
      hosts:
        vm1:
          ansible_host: 172.16.16.65
        vm2:
          ansible_host: 172.16.16.202
        vm3:
          ansible_host: 172.16.16.203

    cloud:
      hosts:
        149.28.65.221:

    onprem:
      children:
        vsphere:

    datacenter:
      children:
        cloud:
        onprem:
