username: "hyoga"

shell: /usr/bin/zsh

guid: 1000

ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKEEL7L9/Qeo0tE9vfbMWF54eydaP+waql4T7EFyjn8s hyoga@typhon.tech"

packages:
  - zsh
  - vim
  - htop
  - ranger
