username: "hyoga"

shell: /usr/bin/zsh

guid: 1000

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDxqj4/uky6U9zh2MYsbJwrd6id1TwTPYrKtyPlBdZICQj5l4ENMy6SGPFgQl7ZZ9zYlXSE0AW5s7a0/jSlCjZuRBMun6orf/nz2TNl+yjL9JB7lbcE9fQZDtDKg2z9GN5q5lWplzxs3bjpfBouxy1vlXQMwS6cwnpvh3gPbh3tbos5HvfW+/t5r6YLm6neWzVxgHizGAvrZVKkoe5ulNjZUyPWgDK+3EqdsKMVFbexdrsZWR1zWn16m0uD1BLLE5ekeyuhjWrLUkZiL9QdKsixHt+uiX9z/ozby7EeG1ExwPujZRENN/k9dZ5jTmL3tvcNMultvSDcDt64H03W9GYNBKnBadRy57Q1cWzUhSsGDTS67EwS0QM2nG6GMGKlMZV6vvvrBuwgiBbrR8dZmYuWzBxs0Mv1CB15eDlbo0UUOa5AEEw+xX/OnIrqJEIBNT3yeTCvvqQhpbGUVdoKNQlDQAFTM23GM1NW6hGwdBS8wZVdCXpXQp3K3QQE+Kri1n0= hyoga@loba"

packages:
  - zsh
  - vim
  - htop
  - ranger
  - tmux
