---
- name: Display content of config.yaml
  ansible.builtin.command: cat config.yaml chdir=/home/{{ username }}/.config/code-server
  register: command_output
  changed_when: command_output.stdout != 0

- name: Print to console
  ansible.builtin.debug:
    msg: "{{ command_output.stdout }}"
