---
- name: Add Hashicorp Packer GPG Key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: 0644
  register: add_apt_key

- name: Add the Hashicorp repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ add_apt_key.dest }}] https://apt.releases.hashhttps://packages.microsoft.com/repos/microsoft-icorp.com/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main
    filename: packer
    state: present

- name: Update the apt cache and Install Packer
  ansible.builtin.apt:
    update_cache: true
    pkg: packer