- name: "Copy SSH Files to the correct location"
  ansible.builtin.include_tasks: copy_ssh_keys.yml

- name: "Installing Packages"
  ansible.builtin.include_tasks: install_packages.yml

- name: "Install RedHat Ansible"
  ansible.builtin.include_tasks: install_ansible.yml

- name: Create Keyring directory
  ansible.builtin.include_tasks: create_keyrings_dir.yml

- name: "Add Hashicorp asc keys to the repo"
  ansible.builtin.include_tasks: add_hashicorp_repo.yml

- name: "Installing Hashicorp Stacks (Terraform, Packer)"
  ansible.builtin.include_tasks: install_hashicorp_stack.yml

- name: "Installing PowerShell"
  ansible.builtin.include_tasks: install_powershell.yml

- name: "Create Git directory"
  ansible.builtin.include_tasks: create_git_directory.yml

- name: "Git clone the boilerplates"
  ansible.builtin.include_tasks: clone_git_boilerplates.yml

- name: "Installing code-server"
  ansible.builtin.include_tasks: install_code_server.yml

- name: "Self-signed cert for code-server"
  ansible.builtin.include_tasks: set_self-signed_cert.yml
    
- name: "Grab config.yaml password generated"
  ansible.builtin.include_tasks: grab_passwd.yml