- name: "Copy SSH Files to the correct location"
  ansible.builtin.include_tasks: copy_ssh_keys.yml

- name: "Installing Packages"
  ansible.builtin.include_tasks: install_packages.yml

- name: "Install RedHat Ansible"
  ansible.builtin.include_tasks: install_ansible.yml

- name: Create Keyring directory
  ansible.builtin.include_tasks: create_keyrings_dir.yml

- name: "Installing Hashicorp Stacks (Terraform, Packer)"
  ansible.builtin.include_tasks: install_hashicorp_stack.yml

- name: "Installing PowerShell"
  ansible.builtin.include_tasks: install_powershell.yml
