---
- name: Copy SSH Keys to remote host
  ansible.builtin.copy:
    src: "{{ ansible_dest }}/roles/code-server/templates/"
    dest: /home/{{ username }}/.ssh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: preserve

- name: Add .local/bin to the Path
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.zshrc
    insertafter: 'LANG'
    line: 'export PATH=$HOME/.local/bin:$PATH'
