- name: Create Docker network
  community.docker.docker_network:
    name: media
    state: present
  register: docker_network

- name: Deploy Docker containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default('always') }}"
    capabilities: "{{ item.capabilities | default(omit) }}"
    sysctls: "{{ item.sysctls | default(omit) }}"
    env: "{{ item.env }}"
    networks: [name: "{{ docker_network.network.Name }}"]
    pull: "{{ item.pull | default(true) }}"
    state: "{{ item.state | default('started') }}"
  loop: "{{ service_definitions }}"
  loop_control:
    label: "{{ item.name }}"
  register: deploy_containers
  notify: Chmod docker sock
