---
- name: "Install the essentials on the target"
  hosts: guests
  become: true
  roles:
    - { role: ../roles/system }
    - role: gantsign.oh-my-zsh
      users:
        - username: hyoga
          oh_my_zsh:
            theme: bira
            update_mode: reminder
            update_frequency: 3
