---
- name: "Install docker containers"
  hosts: docker_hosts
  become: true
  module_defaults:
    community.docker.docker_container:
      restart_policy: always
  
  roles:
    - { role: ../roles/compose }