---
- name: "Install docker and docker-compose on the target"
  hosts: horizon
  become: true

  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_package_state: latest
    docker_users: [hyoga]

  roles:
    - { role: ../roles/system }
    - role: gantsign.oh-my-zsh
      users:
        - username: hyoga
          oh_my_zsh:
            theme: bira
            update_mode: reminder
            update_frequency: 3
    - geerlingguy.pip
    - geerlingguy.docker
    - { role: ../roles/compose }
