- name: Install necessary packages
  ansible.builtin.apt:
    pkg:
      - curl
      - gnupg
      - lsb-release
      - ca-certificates

- name: Add ctop apt key
  ansible.builtin.get_url:
    url: https://azlux.fr/repo.gpg.key
    dest: /etc/apt/trusted.gpg.d/azlux.asc
    mode: 0644
  register: add_apt_key
  # Potentially use tags

- name: Add ctop repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ add_apt_key.dest }}] http://packages.azlux.fr/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main
    filename: ctop
    state: present

- name: Install necessary packages
  ansible.builtin.apt:
    update_cache: true
    pkg: docker-ctop
