---
- name: Restart ssh daemon
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart code-server
  ansible.builtin.service:
    name: code-server@{{ username }}.service
    state: restarted
